apiVersion: v1
kind: Service
metadata:
  name: ph-backend-service
  namespace: dev  
spec:
  selector:
    app: ph-backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8081
  type: NodePort