apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-backend-deployment
  namespace: dev  
  labels: 
    app: ph-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-backend
  template:
    metadata:
      labels:
        app: ph-backend
    spec:
      containers:
      - name: ph-backend
        image: ghcr.io/sergioanastacio/ph-backend:1.0.0
        ports:
        - containerPort: 8080
        - containerPort: 8081