apiVersion: v1
kind: Service
metadata:
  name: cmcio-backend-service
  namespace: dev  
spec:
  selector:
    app: cmcio-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100  # Puedes especificar un puerto en el rango 30000-32767
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30101  # Puedes especificar un puerto en el rango 30000-32767
  type: NodePort