apiVersion: v1
kind: Service
metadata:
  name: cmcio-backend-service
  namespace: dev  
spec:
  selector:
    app: cmcio-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort