apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cmcio-frontend-ingress
  namespace: dev  # Asegúrate de que el namespace sea 'dev'
spec:
  ingressClassName: cmcio-frontend
  rules:
  - host: k8s-load-balancer-676717229.us-west-1.elb.amazonaws.com  # Añade el host aquí
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80