apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmcio-frontend-deployment
  namespace: dev  
  labels: 
    app: cmcio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmcio-frontend
  template:
    metadata:
      labels:
        app: cmcio-frontend
    spec:
      containers:
      - name: cmcio-frontend
        image: ghcr.io/sergioanastacio/cmcio-frontend:1.0.0
        ports:
        - containerPort: 80