apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ph-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SergioAnastacio/cmcio-argocd
    targetRevision: HEAD
    path: dev/frontend/ph
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true